// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: testdata/testpb/basic.proto

package testpb

import (
	_ "github.com/franchb/protoc-gen-go-fieldmeta/fieldmeta/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *string                `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	DisplayName   *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	PasswordHash  *string                `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash" json:"password_hash,omitempty"`
	Ssn           *string                `protobuf:"bytes,4,opt,name=ssn" json:"ssn,omitempty"`
	Role          *string                `protobuf:"bytes,5,opt,name=role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_testdata_testpb_basic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_testpb_basic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_testdata_testpb_basic_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil && x.PasswordHash != nil {
		return *x.PasswordHash
	}
	return ""
}

func (x *User) GetSsn() string {
	if x != nil && x.Ssn != nil {
		return *x.Ssn
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_testdata_testpb_basic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_testpb_basic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_testdata_testpb_basic_proto_rawDescGZIP(), []int{1}
}

type Outer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outer) Reset() {
	*x = Outer{}
	mi := &file_testdata_testpb_basic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer) ProtoMessage() {}

func (x *Outer) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_testpb_basic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer.ProtoReflect.Descriptor instead.
func (*Outer) Descriptor() ([]byte, []int) {
	return file_testdata_testpb_basic_proto_rawDescGZIP(), []int{2}
}

func (x *Outer) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type Outer_Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *int32                 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outer_Inner) Reset() {
	*x = Outer_Inner{}
	mi := &file_testdata_testpb_basic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outer_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer_Inner) ProtoMessage() {}

func (x *Outer_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_testpb_basic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer_Inner.ProtoReflect.Descriptor instead.
func (*Outer_Inner) Descriptor() ([]byte, []int) {
	return file_testdata_testpb_basic_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Outer_Inner) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

var File_testdata_testpb_basic_proto protoreflect.FileDescriptor

const file_testdata_testpb_basic_proto_rawDesc = "" +
	"\n" +
	"\x1btestdata/testpb/basic.proto\x12\x06testpb\x1a\x1afieldmeta/v1/options.proto\"\xd8\x01\n" +
	"\x04User\x12>\n" +
	"\x05email\x18\x01 \x01(\tB(\xa2\xbb\x18\n" +
	"user_email\xba\xbb\x18\remail_address»\x18\x05emailR\x05email\x12+\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\b\xa2\xbb\x18\x04nameR\vdisplayName\x12)\n" +
	"\rpassword_hash\x18\x03 \x01(\tB\x04\xa8\xbb\x18\x01R\fpasswordHash\x12\x1e\n" +
	"\x03ssn\x18\x04 \x01(\tB\f\xa8\xbb\x18\x01»\x18\x04fullR\x03ssn\x12\x18\n" +
	"\x04role\x18\x05 \x01(\tB\x04\xb0\xbb\x18\x01R\x04role\"\a\n" +
	"\x05Empty\"Y\n" +
	"\x05Outer\x12\"\n" +
	"\x04name\x18\x01 \x01(\tB\x0e\xa2\xbb\x18\n" +
	"outer_nameR\x04name\x1a,\n" +
	"\x05Inner\x12#\n" +
	"\x05value\x18\x01 \x01(\x05B\r\xa2\xbb\x18\tinner_valR\x05valueBCZAgithub.com/franchb/protoc-gen-go-fieldmeta/testdata/testpb;testpbb\beditionsp\xe8\a"

var (
	file_testdata_testpb_basic_proto_rawDescOnce sync.Once
	file_testdata_testpb_basic_proto_rawDescData []byte
)

func file_testdata_testpb_basic_proto_rawDescGZIP() []byte {
	file_testdata_testpb_basic_proto_rawDescOnce.Do(func() {
		file_testdata_testpb_basic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_testpb_basic_proto_rawDesc), len(file_testdata_testpb_basic_proto_rawDesc)))
	})
	return file_testdata_testpb_basic_proto_rawDescData
}

var file_testdata_testpb_basic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_testdata_testpb_basic_proto_goTypes = []any{
	(*User)(nil),        // 0: testpb.User
	(*Empty)(nil),       // 1: testpb.Empty
	(*Outer)(nil),       // 2: testpb.Outer
	(*Outer_Inner)(nil), // 3: testpb.Outer.Inner
}
var file_testdata_testpb_basic_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testdata_testpb_basic_proto_init() }
func file_testdata_testpb_basic_proto_init() {
	if File_testdata_testpb_basic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_testpb_basic_proto_rawDesc), len(file_testdata_testpb_basic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_testpb_basic_proto_goTypes,
		DependencyIndexes: file_testdata_testpb_basic_proto_depIdxs,
		MessageInfos:      file_testdata_testpb_basic_proto_msgTypes,
	}.Build()
	File_testdata_testpb_basic_proto = out.File
	file_testdata_testpb_basic_proto_goTypes = nil
	file_testdata_testpb_basic_proto_depIdxs = nil
}
