// Code generated by protoc-gen-go-fieldmeta. DO NOT EDIT.
// version: dev
// source: testdata/testpb/basic.proto

package testpb

import (
	proto "google.golang.org/protobuf/proto"
)

// LogFields_User returns a map of structured logging keys to field values.
func LogFields_User(msg *User) map[string]any {
	if msg == nil {
		return nil
	}
	m := msg.ProtoReflect()
	fds := m.Descriptor().Fields()
	result := make(map[string]any, 2)
	result["user_email"] = m.Get(fds.ByName("email")).Interface()
	result["name"] = m.Get(fds.ByName("display_name")).Interface()
	return result
}

// SensitiveFieldNames_User returns the proto field names marked as sensitive.
func SensitiveFieldNames_User() []string {
	return []string{
		"password_hash",
		"ssn",
	}
}

// RedactSensitive_User returns a deep copy with sensitive fields cleared.
func RedactSensitive_User(msg *User) *User {
	if msg == nil {
		return nil
	}
	clone := proto.Clone(msg).(*User)
	m := clone.ProtoReflect()
	fds := m.Descriptor().Fields()
	m.Clear(fds.ByName("password_hash"))
	m.Clear(fds.ByName("ssn"))
	return clone
}

// FieldDbColumns_User returns a map of proto field name to DB column name.
func FieldDbColumns_User() map[string]string {
	return map[string]string{
		"email": "email_address",
	}
}

// LogFields_Outer returns a map of structured logging keys to field values.
func LogFields_Outer(msg *Outer) map[string]any {
	if msg == nil {
		return nil
	}
	m := msg.ProtoReflect()
	fds := m.Descriptor().Fields()
	result := make(map[string]any, 1)
	result["outer_name"] = m.Get(fds.ByName("name")).Interface()
	return result
}

// LogFields_Outer_Inner returns a map of structured logging keys to field values.
func LogFields_Outer_Inner(msg *Outer_Inner) map[string]any {
	if msg == nil {
		return nil
	}
	m := msg.ProtoReflect()
	fds := m.Descriptor().Fields()
	result := make(map[string]any, 1)
	result["inner_val"] = m.Get(fds.ByName("value")).Interface()
	return result
}
