// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: testdata/testpb/no_options.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plain) Reset() {
	*x = Plain{}
	mi := &file_testdata_testpb_no_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plain) ProtoMessage() {}

func (x *Plain) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_testpb_no_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plain.ProtoReflect.Descriptor instead.
func (*Plain) Descriptor() ([]byte, []int) {
	return file_testdata_testpb_no_options_proto_rawDescGZIP(), []int{0}
}

func (x *Plain) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Plain) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_testdata_testpb_no_options_proto protoreflect.FileDescriptor

const file_testdata_testpb_no_options_proto_rawDesc = "" +
	"\n" +
	" testdata/testpb/no_options.proto\x12\x06testpb\"+\n" +
	"\x05Plain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameBCZAgithub.com/franchb/protoc-gen-go-fieldmeta/testdata/testpb;testpbb\beditionsp\xe8\a"

var (
	file_testdata_testpb_no_options_proto_rawDescOnce sync.Once
	file_testdata_testpb_no_options_proto_rawDescData []byte
)

func file_testdata_testpb_no_options_proto_rawDescGZIP() []byte {
	file_testdata_testpb_no_options_proto_rawDescOnce.Do(func() {
		file_testdata_testpb_no_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_testpb_no_options_proto_rawDesc), len(file_testdata_testpb_no_options_proto_rawDesc)))
	})
	return file_testdata_testpb_no_options_proto_rawDescData
}

var file_testdata_testpb_no_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testdata_testpb_no_options_proto_goTypes = []any{
	(*Plain)(nil), // 0: testpb.Plain
}
var file_testdata_testpb_no_options_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testdata_testpb_no_options_proto_init() }
func file_testdata_testpb_no_options_proto_init() {
	if File_testdata_testpb_no_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_testpb_no_options_proto_rawDesc), len(file_testdata_testpb_no_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_testpb_no_options_proto_goTypes,
		DependencyIndexes: file_testdata_testpb_no_options_proto_depIdxs,
		MessageInfos:      file_testdata_testpb_no_options_proto_msgTypes,
	}.Build()
	File_testdata_testpb_no_options_proto = out.File
	file_testdata_testpb_no_options_proto_goTypes = nil
	file_testdata_testpb_no_options_proto_depIdxs = nil
}
