// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: testdata/testpb/oneof.proto

package testpb

import (
	_ "github.com/franchb/protoc-gen-go-fieldmeta/fieldmeta/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId *string                `protobuf:"bytes,1,opt,name=event_id,json=eventId" json:"event_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_Text
	//	*Event_Binary
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_testdata_testpb_oneof_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_testpb_oneof_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_testdata_testpb_oneof_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventId() string {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return ""
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetText() string {
	if x != nil {
		if x, ok := x.Payload.(*Event_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Event) GetBinary() []byte {
	if x != nil {
		if x, ok := x.Payload.(*Event_Binary); ok {
			return x.Binary
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,oneof"`
}

type Event_Binary struct {
	Binary []byte `protobuf:"bytes,3,opt,name=binary,oneof"`
}

func (*Event_Text) isEvent_Payload() {}

func (*Event_Binary) isEvent_Payload() {}

var File_testdata_testpb_oneof_proto protoreflect.FileDescriptor

const file_testdata_testpb_oneof_proto_rawDesc = "" +
	"\n" +
	"\x1btestdata/testpb/oneof.proto\x12\x06testpb\x1a\x1afieldmeta/v1/options.proto\"\x83\x01\n" +
	"\x05Event\x12'\n" +
	"\bevent_id\x18\x01 \x01(\tB\f\xa2\xbb\x18\bevent_idR\aeventId\x12&\n" +
	"\x04text\x18\x02 \x01(\tB\x10\xa2\xbb\x18\ftext_payloadH\x00R\x04text\x12\x1e\n" +
	"\x06binary\x18\x03 \x01(\fB\x04\xa8\xbb\x18\x01H\x00R\x06binaryB\t\n" +
	"\apayloadBCZAgithub.com/franchb/protoc-gen-go-fieldmeta/testdata/testpb;testpbb\beditionsp\xe8\a"

var (
	file_testdata_testpb_oneof_proto_rawDescOnce sync.Once
	file_testdata_testpb_oneof_proto_rawDescData []byte
)

func file_testdata_testpb_oneof_proto_rawDescGZIP() []byte {
	file_testdata_testpb_oneof_proto_rawDescOnce.Do(func() {
		file_testdata_testpb_oneof_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_testpb_oneof_proto_rawDesc), len(file_testdata_testpb_oneof_proto_rawDesc)))
	})
	return file_testdata_testpb_oneof_proto_rawDescData
}

var file_testdata_testpb_oneof_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testdata_testpb_oneof_proto_goTypes = []any{
	(*Event)(nil), // 0: testpb.Event
}
var file_testdata_testpb_oneof_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testdata_testpb_oneof_proto_init() }
func file_testdata_testpb_oneof_proto_init() {
	if File_testdata_testpb_oneof_proto != nil {
		return
	}
	file_testdata_testpb_oneof_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_Text)(nil),
		(*Event_Binary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_testpb_oneof_proto_rawDesc), len(file_testdata_testpb_oneof_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_testpb_oneof_proto_goTypes,
		DependencyIndexes: file_testdata_testpb_oneof_proto_depIdxs,
		MessageInfos:      file_testdata_testpb_oneof_proto_msgTypes,
	}.Build()
	File_testdata_testpb_oneof_proto = out.File
	file_testdata_testpb_oneof_proto_goTypes = nil
	file_testdata_testpb_oneof_proto_depIdxs = nil
}
