// Code generated by protoc-gen-go-fieldmeta. DO NOT EDIT.
// version: dev
// source: testdata/testpb/oneof.proto

package testpb

import (
	proto "google.golang.org/protobuf/proto"
)

// LogFields_Event returns a map of structured logging keys to field values.
func LogFields_Event(msg *Event) map[string]any {
	if msg == nil {
		return nil
	}
	m := msg.ProtoReflect()
	fds := m.Descriptor().Fields()
	result := make(map[string]any, 2)
	result["event_id"] = m.Get(fds.ByName("event_id")).Interface()
	result["text_payload"] = m.Get(fds.ByName("text")).Interface()
	return result
}

// SensitiveFieldNames_Event returns the proto field names marked as sensitive.
func SensitiveFieldNames_Event() []string {
	return []string{
		"binary",
	}
}

// RedactSensitive_Event returns a deep copy with sensitive fields cleared.
func RedactSensitive_Event(msg *Event) *Event {
	if msg == nil {
		return nil
	}
	clone := proto.Clone(msg).(*Event)
	m := clone.ProtoReflect()
	fds := m.Descriptor().Fields()
	m.Clear(fds.ByName("binary"))
	return clone
}
