// Code generated by protoc-gen-go-fieldmeta. DO NOT EDIT.
// version: dev
// source: testdata/testpb/tags_compat.proto

package testpb

import (
	proto "google.golang.org/protobuf/proto"
)

// LogFields_LegacyUser returns a map of structured logging keys to field values.
func LogFields_LegacyUser(msg *LegacyUser) map[string]any {
	if msg == nil {
		return nil
	}
	m := msg.ProtoReflect()
	fds := m.Descriptor().Fields()
	result := make(map[string]any, 1)
	result["user_login"] = m.Get(fds.ByName("login")).Interface()
	return result
}

// SensitiveFieldNames_LegacyUser returns the proto field names marked as sensitive.
func SensitiveFieldNames_LegacyUser() []string {
	return []string{
		"login",
	}
}

// RedactSensitive_LegacyUser returns a deep copy with sensitive fields cleared.
func RedactSensitive_LegacyUser(msg *LegacyUser) *LegacyUser {
	if msg == nil {
		return nil
	}
	clone := proto.Clone(msg).(*LegacyUser)
	m := clone.ProtoReflect()
	fds := m.Descriptor().Fields()
	m.Clear(fds.ByName("login"))
	return clone
}

// FieldTags_LegacyUser returns a map of proto field name to raw struct tag string.
func FieldTags_LegacyUser() map[string]string {
	return map[string]string{
		"email": "validate:\"required,email\" yaml:\"email\"",
		"age":   "validate:\"gte=0,lte=150\"",
	}
}

// GetFieldTag_LegacyUser returns a single struct tag value for the given field and tag key.
func GetFieldTag_LegacyUser(protoFieldName, tagKey string) string {
	tags := FieldTags_LegacyUser()
	raw, ok := tags[protoFieldName]
	if !ok {
		return ""
	}
	return parseTagValue_fieldmeta(raw, tagKey)
}

// parseTagValue_fieldmeta extracts a single tag value from a raw struct tag string.
func parseTagValue_fieldmeta(raw, key string) string {
	search := key + ":\""
	idx := indexOf_fieldmeta(raw, search)
	if idx < 0 {
		return ""
	}
	// Ensure full key match (not a suffix of another key).
	for idx > 0 && raw[idx-1] != ' ' {
		next := indexOf_fieldmeta(raw[idx+1:], search)
		if next < 0 {
			return ""
		}
		idx = idx + 1 + next
	}
	start := idx + len(search)
	end := indexOf_fieldmeta(raw[start:], "\"")
	if end < 0 {
		return ""
	}
	return raw[start : start+end]
}

// indexOf_fieldmeta returns the index of substr in s, or -1.
func indexOf_fieldmeta(s, substr string) int {
	for i := 0; i+len(substr) <= len(s); i++ {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}
