// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: testdata/testpb/tags_compat.proto

package testpb

import (
	_ "github.com/franchb/protoc-gen-go-fieldmeta/fieldmeta/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LegacyUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Email *string                `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Age   *int32                 `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	// This field uses structured options, NOT tags — should not appear in FieldTags.
	Login         *string `protobuf:"bytes,3,opt,name=login" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LegacyUser) Reset() {
	*x = LegacyUser{}
	mi := &file_testdata_testpb_tags_compat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LegacyUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LegacyUser) ProtoMessage() {}

func (x *LegacyUser) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_testpb_tags_compat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LegacyUser.ProtoReflect.Descriptor instead.
func (*LegacyUser) Descriptor() ([]byte, []int) {
	return file_testdata_testpb_tags_compat_proto_rawDescGZIP(), []int{0}
}

func (x *LegacyUser) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *LegacyUser) GetAge() int32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *LegacyUser) GetLogin() string {
	if x != nil && x.Login != nil {
		return *x.Login
	}
	return ""
}

var File_testdata_testpb_tags_compat_proto protoreflect.FileDescriptor

const file_testdata_testpb_tags_compat_proto_rawDesc = "" +
	"\n" +
	"!testdata/testpb/tags_compat.proto\x12\x06testpb\x1a\x1afieldmeta/v1/options.proto\"\xa8\x01\n" +
	"\n" +
	"LegacyUser\x12@\n" +
	"\x05email\x18\x01 \x01(\tB*\xc2\xc1\x18&validate:\"required,email\" yaml:\"email\"R\x05email\x12.\n" +
	"\x03age\x18\x02 \x01(\x05B\x1c\xc2\xc1\x18\x18validate:\"gte=0,lte=150\"R\x03age\x12(\n" +
	"\x05login\x18\x03 \x01(\tB\x12\xa2\xbb\x18\n" +
	"user_login\xa8\xbb\x18\x01R\x05loginBCZAgithub.com/franchb/protoc-gen-go-fieldmeta/testdata/testpb;testpbb\beditionsp\xe8\a"

var (
	file_testdata_testpb_tags_compat_proto_rawDescOnce sync.Once
	file_testdata_testpb_tags_compat_proto_rawDescData []byte
)

func file_testdata_testpb_tags_compat_proto_rawDescGZIP() []byte {
	file_testdata_testpb_tags_compat_proto_rawDescOnce.Do(func() {
		file_testdata_testpb_tags_compat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_testpb_tags_compat_proto_rawDesc), len(file_testdata_testpb_tags_compat_proto_rawDesc)))
	})
	return file_testdata_testpb_tags_compat_proto_rawDescData
}

var file_testdata_testpb_tags_compat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testdata_testpb_tags_compat_proto_goTypes = []any{
	(*LegacyUser)(nil), // 0: testpb.LegacyUser
}
var file_testdata_testpb_tags_compat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testdata_testpb_tags_compat_proto_init() }
func file_testdata_testpb_tags_compat_proto_init() {
	if File_testdata_testpb_tags_compat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_testpb_tags_compat_proto_rawDesc), len(file_testdata_testpb_tags_compat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_testpb_tags_compat_proto_goTypes,
		DependencyIndexes: file_testdata_testpb_tags_compat_proto_depIdxs,
		MessageInfos:      file_testdata_testpb_tags_compat_proto_msgTypes,
	}.Build()
	File_testdata_testpb_tags_compat_proto = out.File
	file_testdata_testpb_tags_compat_proto_goTypes = nil
	file_testdata_testpb_tags_compat_proto_depIdxs = nil
}
