package generator

import (
	fieldmetav1 "github.com/franchb/protoc-gen-go-fieldmeta/fieldmeta/v1"
	"github.com/franchb/protoc-gen-go-fieldmeta/internal/version"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

// fieldMeta holds extracted option values for a single field.
type fieldMeta struct {
	Field     *protogen.Field
	Log       string // fieldmeta.log
	Sensitive bool   // fieldmeta.sensitive
	Immutable bool   // fieldmeta.immutable
	Db        string // fieldmeta.db
	Mask      string // fieldmeta.mask
	Tags      string // fieldmeta.tags
}

// hasAnyOption returns true if any fieldmeta option is set.
func (fm fieldMeta) hasAnyOption() bool {
	return fm.Log != "" || fm.Sensitive || fm.Immutable || fm.Db != "" || fm.Mask != "" || fm.Tags != ""
}

// messageMeta holds annotated fields for a single message.
type messageMeta struct {
	Message *protogen.Message
	Fields  []fieldMeta
}

// GenerateFile generates a _fieldmeta.pb.go file for a .proto file,
// if any messages have fieldmeta annotations.
func GenerateFile(gen *protogen.Plugin, file *protogen.File) error {
	allMessages := collectAllMessages(file.Messages)
	var annotated []messageMeta

	for _, msg := range allMessages {
		mm := collectMessageMeta(msg)
		if mm != nil {
			annotated = append(annotated, *mm)
		}
	}

	if len(annotated) == 0 {
		return nil // no fieldmeta annotations — skip file
	}

	filename := file.GeneratedFilenamePrefix + "_fieldmeta.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	emitHeader(g, file)

	for _, mm := range annotated {
		emitMessageHelpers(g, mm)
	}

	if needsTagHelpers(annotated) {
		emitTagParserHelpers(g)
	}

	return nil
}

// collectAllMessages recursively flattens all messages, including nested ones.
// Map entry messages are skipped.
func collectAllMessages(messages []*protogen.Message) []*protogen.Message {
	var result []*protogen.Message
	for _, msg := range messages {
		if msg.Desc.IsMapEntry() {
			continue
		}
		result = append(result, msg)
		result = append(result, collectAllMessages(msg.Messages)...)
	}
	return result
}

// collectMessageMeta extracts fieldMeta for all annotated fields in a message.
// Returns nil if no fields have fieldmeta annotations.
func collectMessageMeta(msg *protogen.Message) *messageMeta {
	var fields []fieldMeta
	for _, field := range msg.Fields {
		fm := extractFieldMeta(field)
		if fm.hasAnyOption() {
			fields = append(fields, fm)
		}
	}
	if len(fields) == 0 {
		return nil
	}
	return &messageMeta{Message: msg, Fields: fields}
}

// extractFieldMeta reads all fieldmeta.* extensions from a field's options.
func extractFieldMeta(field *protogen.Field) fieldMeta {
	fm := fieldMeta{Field: field}
	opts := field.Desc.Options()
	if opts == nil {
		return fm
	}
	if proto.HasExtension(opts, fieldmetav1.E_Log) {
		if v, ok := proto.GetExtension(opts, fieldmetav1.E_Log).(string); ok {
			fm.Log = v
		}
	}
	if proto.HasExtension(opts, fieldmetav1.E_Sensitive) {
		if v, ok := proto.GetExtension(opts, fieldmetav1.E_Sensitive).(bool); ok {
			fm.Sensitive = v
		}
	}
	if proto.HasExtension(opts, fieldmetav1.E_Immutable) {
		if v, ok := proto.GetExtension(opts, fieldmetav1.E_Immutable).(bool); ok {
			fm.Immutable = v
		}
	}
	if proto.HasExtension(opts, fieldmetav1.E_Db) {
		if v, ok := proto.GetExtension(opts, fieldmetav1.E_Db).(string); ok {
			fm.Db = v
		}
	}
	if proto.HasExtension(opts, fieldmetav1.E_Mask) {
		if v, ok := proto.GetExtension(opts, fieldmetav1.E_Mask).(string); ok {
			fm.Mask = v
		}
	}
	if proto.HasExtension(opts, fieldmetav1.E_Tags) {
		if v, ok := proto.GetExtension(opts, fieldmetav1.E_Tags).(string); ok {
			fm.Tags = v
		}
	}
	return fm
}

// emitHeader writes the file header with DO NOT EDIT notice.
func emitHeader(g *protogen.GeneratedFile, file *protogen.File) {
	g.P("// Code generated by protoc-gen-go-fieldmeta. DO NOT EDIT.")
	g.P("// version: ", version.Version)
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
}

// needsTagHelpers returns true if any message uses the tags option.
func needsTagHelpers(annotated []messageMeta) bool {
	for _, mm := range annotated {
		for _, fm := range mm.Fields {
			if fm.Tags != "" {
				return true
			}
		}
	}
	return false
}

// filter returns fields matching a predicate.
func filter(fields []fieldMeta, pred func(fieldMeta) bool) []fieldMeta {
	var result []fieldMeta
	for _, fm := range fields {
		if pred(fm) {
			result = append(result, fm)
		}
	}
	return result
}

// Used by helpers.go for qualified identifiers.
var protoPackage = protogen.GoImportPath("google.golang.org/protobuf/proto")
