// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: fieldmeta/v1/options.proto

package fieldmetav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_fieldmeta_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50100,
		Name:          "fieldmeta.v1.log",
		Tag:           "bytes,50100,opt,name=log",
		Filename:      "fieldmeta/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50101,
		Name:          "fieldmeta.v1.sensitive",
		Tag:           "varint,50101,opt,name=sensitive",
		Filename:      "fieldmeta/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50102,
		Name:          "fieldmeta.v1.immutable",
		Tag:           "varint,50102,opt,name=immutable",
		Filename:      "fieldmeta/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50103,
		Name:          "fieldmeta.v1.db",
		Tag:           "bytes,50103,opt,name=db",
		Filename:      "fieldmeta/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50104,
		Name:          "fieldmeta.v1.mask",
		Tag:           "bytes,50104,opt,name=mask",
		Filename:      "fieldmeta/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50200,
		Name:          "fieldmeta.v1.tags",
		Tag:           "bytes,50200,opt,name=tags",
		Filename:      "fieldmeta/v1/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Structured logging key for this field.
	//
	// optional string log = 50100;
	E_Log = &file_fieldmeta_v1_options_proto_extTypes[0]
	// Marks the field as containing sensitive data.
	//
	// optional bool sensitive = 50101;
	E_Sensitive = &file_fieldmeta_v1_options_proto_extTypes[1]
	// Marks the field as immutable after creation.
	//
	// optional bool immutable = 50102;
	E_Immutable = &file_fieldmeta_v1_options_proto_extTypes[2]
	// Database column name mapping.
	//
	// optional string db = 50103;
	E_Db = &file_fieldmeta_v1_options_proto_extTypes[3]
	// Masking behavior hint (e.g. "email", "phone", "full").
	//
	// optional string mask = 50104;
	E_Mask = &file_fieldmeta_v1_options_proto_extTypes[4]
	// Raw struct tag string — migration shim from @gotags.
	//
	// optional string tags = 50200;
	E_Tags = &file_fieldmeta_v1_options_proto_extTypes[5]
)

var File_fieldmeta_v1_options_proto protoreflect.FileDescriptor

const file_fieldmeta_v1_options_proto_rawDesc = "" +
	"\n" +
	"\x1afieldmeta/v1/options.proto\x12\ffieldmeta.v1\x1a google/protobuf/descriptor.proto:1\n" +
	"\x03log\x12\x1d.google.protobuf.FieldOptions\x18\xb4\x87\x03 \x01(\tR\x03log:=\n" +
	"\tsensitive\x12\x1d.google.protobuf.FieldOptions\x18\xb5\x87\x03 \x01(\bR\tsensitive:=\n" +
	"\timmutable\x12\x1d.google.protobuf.FieldOptions\x18\xb6\x87\x03 \x01(\bR\timmutable:/\n" +
	"\x02db\x12\x1d.google.protobuf.FieldOptions\x18\xb7\x87\x03 \x01(\tR\x02db:3\n" +
	"\x04mask\x12\x1d.google.protobuf.FieldOptions\x18\xb8\x87\x03 \x01(\tR\x04mask:3\n" +
	"\x04tags\x12\x1d.google.protobuf.FieldOptions\x18\x98\x88\x03 \x01(\tR\x04tagsBEZCgithub.com/franchb/protoc-gen-go-fieldmeta/fieldmeta/v1;fieldmetav1b\beditionsp\xe8\a"

var file_fieldmeta_v1_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_fieldmeta_v1_options_proto_depIdxs = []int32{
	0, // 0: fieldmeta.v1.log:extendee -> google.protobuf.FieldOptions
	0, // 1: fieldmeta.v1.sensitive:extendee -> google.protobuf.FieldOptions
	0, // 2: fieldmeta.v1.immutable:extendee -> google.protobuf.FieldOptions
	0, // 3: fieldmeta.v1.db:extendee -> google.protobuf.FieldOptions
	0, // 4: fieldmeta.v1.mask:extendee -> google.protobuf.FieldOptions
	0, // 5: fieldmeta.v1.tags:extendee -> google.protobuf.FieldOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	0, // [0:6] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fieldmeta_v1_options_proto_init() }
func file_fieldmeta_v1_options_proto_init() {
	if File_fieldmeta_v1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fieldmeta_v1_options_proto_rawDesc), len(file_fieldmeta_v1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_fieldmeta_v1_options_proto_goTypes,
		DependencyIndexes: file_fieldmeta_v1_options_proto_depIdxs,
		ExtensionInfos:    file_fieldmeta_v1_options_proto_extTypes,
	}.Build()
	File_fieldmeta_v1_options_proto = out.File
	file_fieldmeta_v1_options_proto_goTypes = nil
	file_fieldmeta_v1_options_proto_depIdxs = nil
}
